// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brtmtlwlwipkdhrqkcai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJydG10bHdsd2lwa2RocnFrY2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODk4ODAsImV4cCI6MjA3MTg2NTg4MH0.EREGpucf5Cr3mo7V_9DGdTQfLB2Nu2Zv-q1GeKVAi6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});